### PR TITLE
Add Zoom background size.

### PR DESCRIPTION
**Pull request by benkiel**

### CODE REVIEW

**Comment by typemytype** [comment]
Hehe cool, could you add instagram 1080 x 1080 and teams 1920 x 1080?

**Comment by benkiel** [comment]
Done!

**Comment by benkiel** [comment]
@typemytype tests are failing due to the image link now being bad (this is an issue in the examples on the site too)

**Comment by justvanrossum** [comment]
I know I'm fun at parties, but what if Zoom/Teams/Instagram changes their "ideal" image sizes? A4 will be A4 forever, but these things?

**Comment by justvanrossum** [comment]
Which reminds me: why are the sizes rounded to points? That makes A4 not A4.

**Pull request closed without merging**
