### PR TITLE
Added the ability to create links within a PDF

### PR DESCRIPTION
**Pull request by andyclymer**
Add a link rect with the name of a link on one page, and a link destination location with the same name on another page. The (x,y) location of the link destination defaults to None, in which case the link destination will be placed in the center of the page.

### CODE REVIEW

**Comment by typemytype** [comment]
Should a formatted string also be able to support urls/links?

**Comment by andyclymer** [comment]
That's probably a good idea. Should I take a shot at it? It looks like in the pdfContext there's a moment when I'd be able to get the bounding box for a text box as it's being drawn? I'd have to hunt around a bit but I could try :)

**Comment by typemytype** [comment]
I would like to add `linkText(string, (x, y), urlStr)`

This should also be added to a formattedString. 
This could be stored in the NSAttributedString and used while drawing. The rect of a text with a link could be retrieved with [CTRunGetImageBounds or CTRunGetTypographicBounds](https://developer.apple.com/library/ios/documentation/Carbon/Reference/CTRunRef/index.html#//apple_ref/c/func/CTRunGetImageBounds)

if links are going to be supported `underline`, `strikethrough` and maybe some other text decorations options should be supported....

Links could be really cool: fe to write interactive specimens, and each glyph has a link with robofont-script://<pathToScript.py> so glyphs could be edited directly in RoboFont with a click from a pdf...

cc @justvanrossum

**Comment by justvanrossum** [comment]
Re. `linkDestination()` and `linkRect()`: the documentation is rather sparse. From reading the doc strings I have no idea what this does. What is the `name` argument? How to use these functions?

**Comment by justvanrossum** [comment]
Also, the word `link` suggests URL, which it isn't.

**Comment by typemytype** [comment]
it could be a `name` or an `URL`

A name will jump from the `linkRect` to the `linkDestination`

When an URL is provided it will open the it in the default browser. (see [CGPDFContextSetURLForRect](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGPDFContext/#//apple_ref/c/func/CGPDFContextSetURLForRect))

Testing the difference between a `name` and and `URL` is maybe as simple as testing on 
`"://" in nameOrLink`

**Pull request merged**
