### PR TITLE
Added setuptools to setup packages config so missing submodules are i…

### PR DESCRIPTION
**Pull request by michielkauwatjoe**
…ncluded.

### CODE REVIEW

**Comment by typemytype** [comment]
Im semi following this issue https://github.com/PageBot/PageBot/issues/185

This is indeed strange, just to be sure you dont have a custom setuptools installed in your pip folder? `<user>/Library/Application Support/DrawBot/Pythohn3.7/`

**Comment by michielkauwatjoe** [comment]
@typemytype (answered this earlier but in the issues section) I've erased all setuptools version from ~/Library/Application Support/DrawBot/...; the interface did detect a new 45.2 version of setuptools in one of my virtual environments folders. Also removed that one, now it finds the one shipped with the latest download (Version 3.123)

```
Name: setuptools
Version: 41.2.0
...
Location: /Applications/DrawBot.app/Contents/Resources/lib/python3.7
...
```

Which seems to be missing code. Should the installer detect a system-wide version of setuptools instead?
 
```
-@-@- $ pwd
/Applications/DrawBot.app/Contents/Resources/lib/python3.7/setuptools-41.2.0.dist-info
-@-@- $ ls
INSTALLER            LICENSE              METADATA             RECORD               WHEEL                dependency_links.txt entry_points.txt     top_level.txt        zip-safe
```

local compile:

```
-@-@- $ ls 
__init__.py             archive_util.py         command                 errors.py               gui-64.exe              monkey.py               py31compat.py           script.tmpl             wheel.py
__pycache__             build_meta.py           config.py               extension.py            gui.exe                 msvc.py                 py33compat.py           site-patch.py           windows_support.py
_deprecation_warning.py cli-32.exe              dep_util.py             extern                  installer.py            namespaces.py           py34compat.py           ssl_support.py
_imp.py                 cli-64.exe              depends.py              glob.py                 launch.py               package_index.py        sandbox.py              unicode_utils.py
_vendor                 cli.exe                 dist.py                 gui-32.exe              lib2to3_ex.py           py27compat.py           script (dev).tmpl       version.py
```

**Comment by justvanrossum** [comment]
I think we may need to add

`setuptools>=45.2.0`

to our requirements.txt

**Comment by typemytype** [comment]
Could you test with the latest release? the latest version includes a newer version of setuptools, as set in the requirements.

https://github.com/typemytype/drawbot/releases/tag/3.124

**Comment by MauriceMeilleur** [comment]
Is PageBot part of the install package now? I updated to 3.124 and this script works fine out of the gate without installing PB:

```
from pagebot.document import Document
from pagebot.elements import newRect
from pagebot.conditions import Center2Center, Middle2Middle
from pagebot.toolbox.units import pt
from pagebot.toolbox.color import color

W, H = pt(500, 400)
doc = Document(w=W, h=H, autoPages=1)
page = doc[1]

# Create a new rectangle element with position conditions
newRect(parent=page, fill=color('red'), size=pt(240, 140),
    # Show measure lines on the element.
    showDimensions=True, 
    conditions=[Center2Center(), Middle2Middle()])
# Make the page apply all conditions.
page.solve() 
# Export the document page as png, so it shows as web image.
doc.export('_export/RedSquare.png') 
```
Screen Shot 2020-03-28 at 9 30 39 AM

**Comment by justvanrossum** [comment]
If you had it installed before (even if it didn't quite work in DB) it will still be there. It's not bundled as far as I can see.

**Comment by typemytype** [comment]
pageBot is not bundled. 

If you already did a pip instal of pageBot inside DrawBot or installed pageBot in the same python version (3.7) then it will be accessible inside DrawBot

**Comment by michielkauwatjoe** [comment]
> Could you test with the latest release? the latest version includes a newer version of setuptools, as set in the requirements.
> 
> https://github.com/typemytype/drawbot/releases/tag/3.124

Nope, still the same error;

```
  Using cached tornado-6.0.4.tar.gz (496 kB)
    ERROR: Command errored out with exit status 1:
     command: /Applications/DrawBot.app/Contents/MacOS/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-a5nsjhj_/tornado/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-a5nsjhj_/tornado/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /private/tmp/pip-install-a5nsjhj_/tornado/pip-egg-info
         cwd: /private/tmp/pip-install-a5nsjhj_/tornado/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.pyc", line 19, in <module>
      File "setuptools/dist.pyc", line 28, in <module>
      File "setuptools/extern/__init__.pyc", line 54, in load_module
    ImportError: The 'ordered_set' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

When I navigate to the setuptools-46.1.3.dist-info folder inside the DrawBot Applications folder, there's no code, only text data and metadata. There's no other setuptools folder.

**Comment by michielkauwatjoe** [comment]
@MauriceMeilleur I'd have to check but I'm guessing we installed PageBot in the user library for Python 3.7.  However, you can now install packages through the DrawBot interface which would make it a lot easier for everyone to upgrade to the latest changes. Only there's still a hickup in the installation process.

> Is PageBot part of the install package now? I updated to 3.124 and this script works fine out of the gate without installing PB:
> 
> ```
> from pagebot.document import Document
> from pagebot.elements import newRect
> from pagebot.conditions import Center2Center, Middle2Middle
> from pagebot.toolbox.units import pt
> from pagebot.toolbox.color import color
> 
> W, H = pt(500, 400)
> doc = Document(w=W, h=H, autoPages=1)
> page = doc[1]
> 
> # Create a new rectangle element with position conditions
> newRect(parent=page, fill=color('red'), size=pt(240, 140),
>     # Show measure lines on the element.
>     showDimensions=True, 
>     conditions=[Center2Center(), Middle2Middle()])
> # Make the page apply all conditions.
> page.solve() 
> # Export the document page as png, so it shows as web image.
> doc.export('_export/RedSquare.png') 
> ```
> 
> Screen Shot 2020-03-28 at 9 30 39 AM

**Pull request closed without merging**
