### PR TITLE
add fallbackfont into svg

### LINKED ISSUE #274: svg fallback fonts
use the fallback font, if set as fallback in svg

requested here: https://forum.drawbot.com/topic/145/setting-fallback-font-for-text-in-svg

### PR DESCRIPTION
**Pull request by typemytype**
Fixes #274

### CODE REVIEW

**Comment by typemytype** [comment]
still todo: add test

**Comment by typemytype** [comment]
tests have to be review in general... as they fail massively based on the OS version

**Comment by justvanrossum** [comment]
Still, a test for this would be good. And I doubt this particular test will fall into the category that depends on the OS version.

Other than that: looking good.

**Comment by typemytype** [comment]
test added!

**Pull request merged**
