### PR TITLE
Building on El Capitan

### PR DESCRIPTION
**Pull request by jenskutilek**
I tried to build DrawBot on El Cap, and had to change the "super" function to use objc.super for classes inheriting from Cocoa classes.

### CODE REVIEW

**Comment by typemytype** [comment]
this is a similar request as @karstenw did, see https://github.com/typemytype/drawbot/pull/20
would this also make DrawBot run on 10.6+, could you test?

thanks

**Comment by jenskutilek** [comment]
I will try to find a 10.6 machine and test ;)

**Comment by karstenw** [comment]
I have a 10.6 machine. Just add an url to a binary.

**Comment by jenskutilek** [comment]
Here's a binary: https://www.dropbox.com/s/gfpf75i2lh3evzv/drawbot.zip?dl=0

Let me know if it works on 10.6.

**Comment by jenskutilek** [comment]
On El Capitan, the System Integrity Protection (SIP) interferes with the py2app build, because the SIP "protected" status is copied with the files while building the app bundle. Then you suddenly don't have write access to your own app bundle, and thus the build process aborts.

I worked around this by setting up a virtual Python environment and building with that. I hope this doesn't complicate things further ;)

**Comment by karstenw** [comment]
It does not run on 10.6.

The first obstacle is the Info.plist "Minimum system version" with a value of 10.9. Tweaked to 10.6. Please delete this entry. It is not needed.

You should get rid off the aliased version. The python executable is soft linked to your virtenv. That way it'll only run on your machine.

```
% ll ./DrawBot.app/Contents/MacOS/
total 216
drwxr-xr-x@ 4 karstenw  staff     136 Jan 28 16:50 .
drwxr-xr-x@ 7 karstenw  staff     238 Jan 28 17:02 ..
-rwxr-xr-x@ 1 karstenw  staff  103952 Jan 28 16:36 DrawBot
lrwxr-xr-x@ 1 karstenw  staff      48 Jan 28 16:50 python -> /Users/jenskutilek/Python/drawbot/env/bin/python
```

On 10.10. I saw some problems too when building an app. I resolved it by building several times untill the last line said the build was ok.

You could try to compile my Drawbot fork [https://github.com/karstenw/drawbot](https://github.com/karstenw/drawbot) It compiles on 10.6 and 10.10 but misses the changes since 2015-08.

**Comment by jenskutilek** [comment]
I can't find a way to include a full Python environment in the app bundle. Followed a [tutorial](https://www.metachris.com/2015/11/create-standalone-mac-os-x-applications-with-python-and-py2app/) and the resulting app still only contains a python binary linked to the virtual environment. This seems to have changed between versions (of Mac OS X or py2app?), as the newest comment in the tutorial hints at.

Without a virtual environment, the app cannot be built due to SIP ... this is where I'm out of ideas ...

**Comment by karstenw** [comment]
After some googling around:

### sip disabling is needed for el capitan & py2app
https://forums.developer.apple.com/thread/6987

### how to disable sip
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

When I read that stuff I'm glad that 10.6 is still my workhorse and 10.10 is so annoying that I boot it only once a month to build some py2apps.

**Comment by justvanrossum** [comment]
@jenskutilek,, @typemytype, how relevant is this PR today? Should we close it?

**Comment by jenskutilek** [comment]
@justvanrossum what system version are you building DrawBot on? I guess if we can build on 10.12 and 10.13, we may close this. But I expect the modification of the `super` function to be needed there as well.

In the meantime I found out that the SIP problem goes away if you install an additional copy of `py2app`, ignoring the pre-installed module:

```bash
$ pip install --user --ignore-installed py2app
```

**Comment by typemytype** [comment]
you can build on any system...
from 10.11+ its advised to install a custom python with all required packages
the system python is will only work on that machine.. (these are my finding after given up the system python after a day...)

**Comment by jenskutilek** [comment]
I successfully built from the master branch on 10.12, so I guess we can close this PR. I got a warning in the console though, perhaps it is important:

```Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.```

**Pull request closed without merging**
