### PR TITLE
Fix for #261: don't try to install fonts from paths, but build NSCTFont directly from file

### LINKED ISSUE #261: Ad-hoc installation of font works every 2nd time
```
my_text = FormattedString(
    'I love DrawBot',
    font='my_font.otf')
    
text(my_text, (100, 100))
```

This works the first time, then fails with
```*** DrawBot warning: font: 'my_font' is not installed, back to the fallback font: 'LucidaGrande' ***```
Then works again, then fails … etc.

### PR DESCRIPTION
**Pull request by justvanrossum**
- When using font paths, don't try to install, but make NSCTFont object directly from file
- Add support for ttc/otc/dfont for font paths (this adds fontNumber properties/arguments in various places)
- Some refactoring with the font properties (such as fontDescender) to reduce code
- Delete skipped fontPath.svg test file

This should fix #261

### CODE REVIEW

**Comment by justvanrossum** [comment]
I was hoping this would also fix #112, but it doesn't :(

**Comment by typemytype** [comment]
ooh cool!

I would deprecate these callbacks: https://github.com/typemytype/drawbot/blob/improve-ttc-and-fix-261/drawBot/drawBotDrawingTools.py#L2215

maybe deprecate hard: they dont need to work anymore
this will also remove all the `_tempInstalledFonts` references in the drawingTool class 

about fixing #112: There is no caching anymore in DrawBot and by the OS, so different fonts with the same postscript name should appear different from each other... strange

**Comment by justvanrossum** [comment]
People may be using `installFont()`, so I would prefer to leave it for a while and emit a deprecation warning.

> about fixing #112: There is no caching anymore in DrawBot and by the OS, so different fonts with the same postscript name should appear different from each other... strange

Well apparently there is, so the "by the OS" is not true (the DB cache gets reset after each drawing). I have an idea I want to try, but that will be for another PR (if it works at all).

**Comment by justvanrossum** [comment]
Ok, I think this is good to go.

**Pull request merged**
