### PR TITLE
support for url links in a pdf doc

### PR DESCRIPTION
**Pull request by typemytype**
todo: ~~add the link in svgContext~~ done

### CODE REVIEW

**Comment by typemytype** [comment]
fixes https://github.com/typemytype/drawbot/issues/365

**Comment by frankrolf** [comment]
Cool! Thank you! It works 😎

**Comment by typemytype** [comment]
fixing https://github.com/typemytype/drawbot/issues/369#issuecomment-609800513

**Comment by typemytype** [comment]
changlog text:

```
- Adding `linkURL(url, (x, y, w, h))`.
- Adding `url(url)` and `formattedString.url(url)`.
- Improve support for `underline`.
```

**Pull request merged**
