### PR TITLE
improve kern and tracking

### LINKED ISSUE #371: Turning Kerning off
Hi guys!

I was wondering if there is a method for turning kerning *off?* It seems to be on by default all the time (which usually is a good thing!) but sometimes I want to have control over whether it is on or off.

The following code still results in a string with kerning on, when I would expect it to be off:
```python
import drawBot as db

db.newPage(500,100)
s = db.FormattedString("AVAVATo",
    font="SourceSerifPro-Bold.otf",
    fontSize=100,
    openTypeFeatures={"kern": False}
)

db.text(s, (20,20))
```

Result:
image

Expected (shown in FontGoggles):
image

[DrawBot Error.zip](https://github.com/typemytype/drawbot/files/4439743/DrawBot.Error.zip)

Is there another method I should be using?

Thanks!

### PR DESCRIPTION
**Pull request by typemytype**
fixes #371 

kernAndTrack

todo: add test

### CODE REVIEW

**Comment by justvanrossum** [comment]
A test case would be nice.

**Comment by typemytype** [comment]
tests added!

and improved OT support for svg

**Comment by colinmford** [comment]
I LOVE IT

**Comment by typemytype** [comment]
change log text:


```
- Improve support for kern feature.
- Seperate tracking from kerning.
```

**Comment by colinmford** [comment]
Is there anything we're still waiting on for this issue?

**Pull request merged**
