### PR TITLE
don’t do `from AppKit import *`

### PR DESCRIPTION
**Pull request by schriftgestalt**
I hope I got everything. Please run tests, I can’t build DrawBot.app.

### CODE REVIEW

**Comment by justvanrossum** [comment]
Thanks Georg! I'll test.

**Comment by justvanrossum** [comment]
Works just fine, thanks again! DB on Py 2.7 starts up as fast as the Py3 version. And it seems the Py3 version also got a little quicker to start up.

**Comment by typemytype** [comment]
super("!")

**Comment by schriftgestalt** [comment]
Now someone needs to edit the code samples to not include the slow line.

**Pull request merged**
