### PR TITLE
don't use apples prefix

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by justvanrossum** [comment]
Thanks, I noticed that, too, and didn't get round to fix that.

**Comment by justvanrossum** [comment]
All sane non-Cocoa frameworks that subclass NSObject use a prefix that is not NS or UI...

**Comment by schriftgestalt** [comment]
The conversion in Cocoa is to use a private (mostly) two letter prefix (because there is no namespace in objectiveC). So the correct Cocoa way would be to use the prefix for all NSObject subclasses. Having the super class in the class name is a bit unusual.

**Comment by justvanrossum** [comment]
I'll change it, though.

**Pull request merged**
